SELECT c.CAR_ID, 
       c.CAR_TYPE, 
       ROUND(c.DAILY_FEE * 30 * (1 - (COALESCE(d.DISCOUNT_RATE, 0) / 100))) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d
ON c.CAR_TYPE = d.CAR_TYPE AND d.DURATION_TYPE = '30일 이상'
WHERE (c.CAR_TYPE = '세단' OR c.CAR_TYPE = 'SUV')
AND NOT EXISTS (SELECT 1 
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h 
                WHERE h.CAR_ID = c.CAR_ID 
                AND ((h.START_DATE BETWEEN '2022-11-01' AND '2022-11-30') 
                OR (h.END_DATE BETWEEN '2022-11-01' AND '2022-11-30') 
                OR ('2022-11-01' BETWEEN h.START_DATE AND h.END_DATE)
                OR ('2022-11-30' BETWEEN h.START_DATE AND h.END_DATE)))
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, c.CAR_TYPE, c.CAR_ID DESC;
